language: cpp

# OS config, depends on actual 'os' in build matrix
dist: xenial

stages:
  - check
  - build

env:
  global:
    - SCONS_CACHE=$HOME/.scons_cache/$TRAVIS_BRANCH
    - SCONS_CACHE_LIMIT=1024
    - OPTIONS="debug_symbols=no verbose=yes progress=no builtin_libpng=yes"
    - secure: "uch9QszCgsl1qVbuzY41P7S2hWL2IiNFV4SbAYRCdi0oJ9MIu+pVyrQdpf3+jG4rH6j4Rffl+sN17Zz4dIDDioFL1JwqyCqyCyswR8uACC0Rr8gr4Mi3+HIRbv+2s2P4cIQq41JM8FJe84k9jLEMGCGh69w+ibCWoWs74CokYVA="

cache:
  directories:
    - $SCONS_CACHE

matrix:
  include:
    - name: Static checks (clang-format) + Documentation checks
      stage: check
      env: STATIC_CHECKS=yes
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-format-8

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      unset SCONS_CACHE;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pyenv global 3.7.1 system;
      pip3 install --user scons;
    fi
  - scons --version
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PLATFORM" = "android" ]; then
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64;
      export PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:${PATH};
      java -version;
      misc/travis/android-tools-linux.sh;
    fi

before_script:
  - if [ "$PLATFORM" = "android" ]; then
      export ANDROID_HOME=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-sdk;
      export ANDROID_NDK_ROOT=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-ndk;
    fi

script:
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      sh ./misc/travis/clang-format.sh &&
      doc/tools/makerst.py --dry-run doc/classes modules;
    else
      scons -j2 CC=$CC CXX=$CXX platform=$PLATFORM tools=$TOOLS target=$TARGET $OPTIONS $EXTRA_ARGS &&
      if [ "$TEST_PROJECT" = "yes" ]; then
        git clone --depth 1 "https://github.com/godotengine/godot-tests.git";
        sed -i "s:custom_template/release=\"\":custom_template/release=\"$(readlink -e bin/godot_server.x11.opt.tools.64)\":" godot-tests/tests/project_export/export_presets.cfg;
        godot-tests/tests/project_export/test_project.sh "bin/godot_server.x11.opt.tools.64";
      fi
    fi
