#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

# Thirdparty source files

thirdparty_dir = "#thirdparty/spirv-reflect/"
thirdparty_sources = [
    "spirv_reflect.c",
]

thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()

env_thirdparty.add_source_files(env.servers_sources, thirdparty_sources)

env.Prepend(CPPPATH=["#thirdparty/spirv/include"])
env.Append(CPPDEFINES=["SPIRV_REFLECT_USE_SYSTEM_SPIRV_H"])
